import type { NextPage } from "next"
import Head from "next/head"
// import Image from "next/image"
import Link from "next/link"

import styles from "@styles/Home.module.scss"
import Counting from "@components/Counting"

// eslint-disable-next-line no-unused-vars, @typescript-eslint/no-unused-vars
const Home: NextPage = (_props) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Counting />
      <div className="gradient-wrapper">
        <div className="gradient purple"></div>
        <div className="gradient orange"></div>
        <div className="gradient yellow"></div>
      </div>

      <div className={styles.title}>
        <Link href="/hello">
          <a>
            <h1>Hello.</h1>
          </a>
        </Link>
      </div>
    </>
  )
}

export default Home
